version: "3.8"

services:

        windoc-sofia-server:
                build: ./
                image: windoc-sofia-server
                container_name: windoc-sofia-server
                hostname: windoc-sofia-server
                restart: always
                env_file:
                        - .env
                volumes:
                        - ./app:/app
                ports:
                        - "1245:1245"
